apiVersion: apps/v1
kind: Deployment
metadata:
  name: cupidcooks
  labels:
    app: cupidcooks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cupidcooks
  template:
    metadata:
      labels:
        app: cupidcooks
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: cupidcooks
        image: parthsinha90/cupidcooks-frontend:latest
        ports:
        - containerPort: 4321
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          
