apiVersion: v1
kind: Service
metadata:
  name: cupidcooks-nodeport
  labels:
    app: cupidcooks
spec:
  selector:
    app: cupidcooks
  ports:
  - name: http
    port: 80
    targetPort: 4321
    nodePort: 30080
  type: NodePort